// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg1ANj-xZi44oNBU1FMMv2pSNksYw_zsE',
    appId: '1:908898805815:web:b967b958625e39d31477b2',
    messagingSenderId: '908898805815',
    projectId: 'siteassesstment',
    authDomain: 'siteassesstment.firebaseapp.com',
    storageBucket: 'siteassesstment.firebasestorage.app',
    measurementId: 'G-3YKCNMHQCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25zu09TxCelaUQqwjdLo00ex_ahENywU',
    appId: '1:908898805815:android:dee2ada18562a3d61477b2',
    messagingSenderId: '908898805815',
    projectId: 'siteassesstment',
    storageBucket: 'siteassesstment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkmkctnWaB_L20Vw2kBOFSiFfW-sVZoko',
    appId: '1:908898805815:ios:5bb03410bd64578a1477b2',
    messagingSenderId: '908898805815',
    projectId: 'siteassesstment',
    storageBucket: 'siteassesstment.firebasestorage.app',
    iosBundleId: 'com.example.siteAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkmkctnWaB_L20Vw2kBOFSiFfW-sVZoko',
    appId: '1:908898805815:ios:5bb03410bd64578a1477b2',
    messagingSenderId: '908898805815',
    projectId: 'siteassesstment',
    storageBucket: 'siteassesstment.firebasestorage.app',
    iosBundleId: 'com.example.siteAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg1ANj-xZi44oNBU1FMMv2pSNksYw_zsE',
    appId: '1:908898805815:web:b01fd23d477c29051477b2',
    messagingSenderId: '908898805815',
    projectId: 'siteassesstment',
    authDomain: 'siteassesstment.firebaseapp.com',
    storageBucket: 'siteassesstment.firebasestorage.app',
    measurementId: 'G-W8FK3MMKFZ',
  );
}
